"""initial migration

Revision ID: 134c913bac35
Revises: 
Create Date: 2025-06-28 04:56:57.344771

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '134c913bac35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('shop_id', sa.String(length=255), nullable=True),
    sa.Column('shop_name', sa.String(length=255), nullable=True),
    sa.Column('file', sa.String(length=255), nullable=True),
    sa.Column('file_data', mysql.LONGBLOB(), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=True),
    sa.Column('updatedAt', sa.DateTime(), nullable=True),
    sa.Column('total_all', sa.Integer(), nullable=True),
    sa.Column('total_pos', sa.Integer(), nullable=True),
    sa.Column('total_neg', sa.Integer(), nullable=True),
    sa.Column('persen_pos', sa.Float(), nullable=True),
    sa.Column('toko_label', sa.String(length=255), nullable=True),
    sa.Column('aspek', sa.String(length=255), nullable=True),
    sa.Column('persen_tertinggi', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    # ### end Alembic commands ###
