"""Add file_data as blob to Review

Revision ID: 265987c96638
Revises: 787d13b4c013
Create Date: 2025-06-21 00:35:03.150377

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '265987c96638'
down_revision = '787d13b4c013'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', sa.LargeBinary(), nullable=False))
        batch_op.drop_column('file')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', mysql.VARCHAR(collation='armscii8_bin', length=255), nullable=False))
        batch_op.drop_column('file_data')

    # ### end Alembic commands ###
