"""change shop_name to shop_url

Revision ID: 7940007fb90b
Revises: e4df29a331cc
Create Date: 2025-06-28 14:27:19.570121

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7940007fb90b'
down_revision = 'e4df29a331cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_url', sa.String(length=255), nullable=True))
        batch_op.drop_column('shop_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shop_name', mysql.VARCHAR(collation='armscii8_bin', length=255), nullable=True))
        batch_op.drop_column('shop_url')

    # ### end Alembic commands ###
