"""add persen aspek

Revision ID: 8ff8816f48c9
Revises: 3c0b04d40cee
Create Date: 2025-07-02 21:14:39.407192

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ff8816f48c9'
down_revision = '3c0b04d40cee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.alter_column('product',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               nullable=False)
        batch_op.alter_column('review',
               existing_type=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               type_=sa.Text(),
               nullable=False)
        batch_op.alter_column('rating',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('reviewAt',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.alter_column('model_name',
               existing_type=mysql.VARCHAR(charset='armscii8', collation='armscii8_bin', length=100),
               nullable=False)
        batch_op.alter_column('accuracy',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('precision',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('recall',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('f1_score',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aspek_persen', sa.Text(), nullable=True))
        batch_op.drop_column('detail')

    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('file_data',
               existing_type=mysql.LONGBLOB(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.alter_column('file_data',
               existing_type=sa.LargeBinary(),
               type_=mysql.LONGBLOB(),
               existing_nullable=True)

    with op.batch_alter_table('prediction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detail', mysql.TEXT(collation='armscii8_bin'), nullable=True))
        batch_op.drop_column('aspek_persen')

    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.alter_column('f1_score',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('recall',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('precision',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('accuracy',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('model_name',
               existing_type=mysql.VARCHAR(charset='armscii8', collation='armscii8_bin', length=100),
               nullable=True)

    with op.batch_alter_table('dataset', schema=None) as batch_op:
        batch_op.alter_column('reviewAt',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('rating',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('review',
               existing_type=sa.Text(),
               type_=mysql.MEDIUMTEXT(charset='utf8mb4', collation='utf8mb4_unicode_ci'),
               nullable=True)
        batch_op.alter_column('product',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_unicode_ci', length=255),
               nullable=True)

    # ### end Alembic commands ###
