"""update tables name

Revision ID: aa99175acd18
Revises: 1e0fba838050
Create Date: 2025-06-21 00:54:21.714035

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa99175acd18'
down_revision = '1e0fba838050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('evaluationAt', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prediction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('total_review', sa.Integer(), nullable=True),
    sa.Column('total_pos', sa.Integer(), nullable=True),
    sa.Column('total_neg', sa.Integer(), nullable=True),
    sa.Column('persen_pos', sa.Float(), nullable=True),
    sa.Column('label_toko', sa.String(length=30), nullable=True),
    sa.Column('aspek_utama', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('prediction_result')
    op.drop_table('model_evaluation')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('model_evaluation',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('model_name', mysql.VARCHAR(collation='armscii8_bin', length=100), nullable=False),
    sa.Column('accuracy', mysql.FLOAT(), nullable=True),
    sa.Column('precision', mysql.FLOAT(), nullable=True),
    sa.Column('recall', mysql.FLOAT(), nullable=True),
    sa.Column('f1_score', mysql.FLOAT(), nullable=True),
    sa.Column('evaluationAt', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='armscii8_bin',
    mysql_default_charset='armscii8',
    mysql_engine='InnoDB'
    )
    op.create_table('prediction_result',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('review_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.Column('total_review', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_pos', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_neg', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('persen_pos', mysql.FLOAT(), nullable=True),
    sa.Column('label_toko', mysql.VARCHAR(collation='armscii8_bin', length=30), nullable=True),
    sa.Column('aspek_utama', mysql.VARCHAR(collation='armscii8_bin', length=50), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], name=op.f('prediction_result_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='armscii8_bin',
    mysql_default_charset='armscii8',
    mysql_engine='InnoDB'
    )
    op.drop_table('prediction')
    op.drop_table('evaluation')
    # ### end Alembic commands ###
