"""update

Revision ID: c276ba5e5318
Revises: 164c43e8c8b2
Create Date: 2025-06-24 02:12:16.557634

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c276ba5e5318'
down_revision = '164c43e8c8b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('training_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_review', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('positif', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('negatif', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('persen_positif', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('label_toko', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('aspek_tertinggi', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('jumlah_aspek', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('persen_aspek', sa.Float(), nullable=True))
        batch_op.alter_column('accuracy',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('precision',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('recall',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('f1_score',
               existing_type=mysql.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('evaluation', schema=None) as batch_op:
        batch_op.alter_column('f1_score',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('recall',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('precision',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('accuracy',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.drop_column('persen_aspek')
        batch_op.drop_column('jumlah_aspek')
        batch_op.drop_column('aspek_tertinggi')
        batch_op.drop_column('label_toko')
        batch_op.drop_column('persen_positif')
        batch_op.drop_column('negatif')
        batch_op.drop_column('positif')
        batch_op.drop_column('total_review')
        batch_op.drop_column('training_time')

    # ### end Alembic commands ###
